# Generated by Django 5.1.7 on 2025-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
