# Generated by Django 4.2.15 on 2025-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(default='', help_text="Enter each step in the format 'Step (number): (instructions)'"),
        ),
    ]
